### ISSUE TITLE
Citation format

### ISSUE THREAD

**Issue by danfbflynn** [NCEAS/commdyn#9]
See Scott's comments in Word file about correct formatting for MEE... 

http://www.methodsinecologyandevolution.org/view/0/authorGuidelines.html#Formatting

[Endnote style here](http://endnote.com/downloads/styles?title_op=contains&title=ecology+and+evolution&tid_op=or&tid=All&field_style_publisher_value_op=contains&field_style_publisher_value=)

[MEE style here, I think](https://github.com/seananderson/bst/blob/master/mee.bst)

**Comment by laurenmh** [comment]
Yeah, I wasn't sure how to get the formatting right with an Rmd file so had left it for the time being. Dan, do you know how to use the .bst file with markdown? This is a new frontier for me.

**Comment by cboettig** [comment]
You'll probably find it's easiest to use the `.csl` style file for MEE with rmarkdown/pandoc rather than .bst. 

`.csl` file here: https://github.com/citation-style-language/styles/blob/master/methods-in-ecology-and-evolution.csl

Just add that to the repo and add 

```yaml
csl: methods-in-ecology-and-evolution.csl
```

to the top level of your yaml header and you should be good to go

**Comment by danfbflynn** [comment]
Super, thanks Carl -- works perfectly.

**Comment by laurenmh** [comment]
Thanks Carl and Dan!
